adminUser:
  password: local:dev-cluster-jstrachan/adminUser:password
  username: admin
docker:
  password: local:dev-cluster-jstrachan/docker:password
  url: https://index.docker.io/v1/
  username: jenkinsxbot
enableDocker: true
gitProvider: github
gpg: {}
pipelineUser:
  github:
    host: github.com
    token: local:dev-cluster-jstrachan/pipelineUser-github:token
    username: jenkins-x-bot-test
prow:
  hmacToken: local:dev-cluster-jstrachan/prow:hmacToken
